#!/bin/sh
set -ex

apt-get update
apt-get install --yes \
  ca-certificates \
  curl

# Install alertmanager-maintenance-scheduler
useradd -r -d /opt/alertmanager-maintenance-scheduler ams

mkdir -p /opt/alertmanager-maintenance-scheduler
mv /alertmanager-maintenance-scheduler /opt/alertmanager-maintenance-scheduler

chown -R ams /opt/alertmanager-maintenance-scheduler

# Clean
apt-get remove --purge curl --yes
apt-get autoremove --purge --yes
apt-get clean --yes

# CIS Benchmarking
sed -i 's/^PASS_MAX_DAYS.*$/PASS_MAX_DAYS   60/g' /etc/login.defs
sed -i 's/^PASS_MIN_DAYS.*$/PASS_MIN_DAYS   7/g' /etc/login.defs
sed -i 's/^UMASK.*$/UMASK   027/g' /etc/login.defs
